baseURL = "https://asadjeewa.github.io/"
languageCode = "en-us"
title = "Asad Jeewa â€” Academic"
theme = "lithium"

# Optional extras
# Author info
[author]
    name = "Asad Jeewa"
    email = "your-email@example.com"

# Menu (example for top navigation)
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2